PLAN_TYPE_BASIC = 'BASIC'
PLAN_TYPE_STANDARD = 'STANDARD'
PLAN_TYPE_AI = 'AI'
PLAN_TYPE_PREMIUM = 'PREMIUM'

SUBSCRIPTION_ACTIVE = 'ACTIVE'
SUBSCRIPTION_INACTIVE = 'INACTIVE'
SUBSCRIPTION_EXPIRED = 'EXPIRED'
SUBSCRIPTION_CANCELLED = 'CANCELLED'
SUBSCRIPTION_PENDING = 'PENDING'

PLAN_TYPE_CHOICES = (
    (PLAN_TYPE_BASIC, 'Basic'),
    (PLAN_TYPE_STANDARD, 'Premium'),
    (PLAN_TYPE_AI, 'AI'),
    (PLAN_TYPE_PREMIUM, 'Premium'),
)

SUBSCRIPTION_STATUS_CHOICES = (
    (SUBSCRIPTION_ACTIVE, 'Active'),
    (SUBSCRIPTION_INACTIVE, 'Inactive'),
    (SUBSCRIPTION_EXPIRED, 'Expired'),
    (SUBSCRIPTION_CANCELLED, 'Cancelled'),
    (SUBSCRIPTION_PENDING, 'Pending'),
)
