# Generated by Django 4.2.30 on 2026-06-28 15:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_websitesetup_plan_type'),
        ('hospitals', '0009_doctor_title_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='review_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='hospitals.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hospitals.doctor')),
                ('website_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reviews', to='core.websitesetup')),
            ],
            options={
                'db_table': 'hospital_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
