import { Waves, Leaf, MoonStar, Flower2, Sun, Gem, Sunset, Cloud, TreePine, Circle, Sparkles, HeartPulse, Stethoscope, Star, MountainSnow, Lock } from 'lucide-react'
import type { ThemeSettings } from '@/components/hospital/customization/types'

export const DEFAULT_THEME: ThemeSettings = {
  primaryColor: '#2563eb',
  backgroundColor: '#f8fafc',
  surfaceColor: '#ffffff',
  surfaceAltColor: '#f1f5f9',
  textColor: '#0f172a',
  mutedTextColor: '#475569',
  borderColor: '#e2e8f0',
  linkColor: '#2563eb',
  buttonPrimaryColor: '#2563eb',
  buttonPrimaryTextColor: '#ffffff',
  buttonPrimaryHoverColor: '#1d4ed8',
  buttonSecondaryColor: '#ffffff',
  buttonSecondaryTextColor: '#1d4ed8',
  buttonSecondaryBorderColor: '#bfdbfe',
  buttonSecondaryHoverColor: '#eff6ff',
  inputBackgroundColor: '#f8fafc',
  inputBorderColor: '#cbd5e1',
  inputFocusColor: '#2563eb',
  fontFamily: 'Inter',
  fontSize: '16px',
  fontStyle: 'normal',
  chatbotName: 'Hospital Medical AI',
  chatbotColor: '#2563eb',
  borderRadius: '0.5rem',
  emergencyNumber: '911',
}

export const AVAILABLE_FONTS = [
  { value: 'Inter', label: 'Inter', description: 'Clean & Modern' },
  { value: 'Roboto', label: 'Roboto', description: 'Professional' },
  { value: 'Outfit', label: 'Outfit', description: 'Friendly & Rounded' },
  { value: 'Nunito', label: 'Nunito', description: 'Soft & Approachable' },
  { value: 'Poppins', label: 'Poppins', description: 'Geometric & Bold' },
  { value: 'Lato', label: 'Lato', description: 'Warm & Humanist' },
  { value: 'Montserrat', label: 'Montserrat', description: 'Strong & Contemporary' },
  { value: 'Open Sans', label: 'Open Sans', description: 'Neutral & Readable' },
  { value: 'Source Sans 3', label: 'Source Sans 3', description: 'Versatile & Clear' },
  { value: 'DM Sans', label: 'DM Sans', description: 'Minimal & Crisp' },
  { value: 'Manrope', label: 'Manrope', description: 'Technical & Sharp' },
  { value: 'Plus Jakarta Sans', label: 'Plus Jakarta Sans', description: 'Modern & Balanced' },
  { value: 'Figtree', label: 'Figtree', description: 'Fresh & Clean' },
  { value: 'Playfair Display', label: 'Playfair Display', description: 'Elegant & Serif' },
  { value: 'Merriweather', label: 'Merriweather', description: 'Readable & Classic' },
  { value: 'Lora', label: 'Lora', description: 'Literary & Refined' },
  { value: 'Cormorant Garamond', label: 'Cormorant Garamond', description: 'Luxury & Timeless' },
  { value: 'EB Garamond', label: 'EB Garamond', description: 'Classic & Editorial' },
  { value: 'JetBrains Mono', label: 'JetBrains Mono', description: 'Technical & Precise' },
  { value: 'Fira Code', label: 'Fira Code', description: 'Modern & Structured' },
]

export const FONT_SIZES = [
  { value: '13px', label: 'XSmall (13px)' },
  { value: '14px', label: 'Small (14px)' },
  { value: '16px', label: 'Normal (16px)' },
  { value: '18px', label: 'Large (18px)' },
  { value: '20px', label: 'XLarge (20px)' },
]

export const BORDER_RADIUS_OPTIONS = [
  { value: '0rem', label: 'Sharp', description: '0px – No rounding' },
  { value: '0.25rem', label: 'Subtle', description: '4px – Slight rounding' },
  { value: '0.5rem', label: 'Rounded', description: '8px – Standard' },
  { value: '0.75rem', label: 'Smooth', description: '12px – Softer feel' },
  { value: '1rem', label: 'Pill', description: '16px – Very rounded' },
]

export const PRESET_THEMES: { name: string; icon: React.ElementType; theme: Partial<ThemeSettings> }[] = [
  {
    name: 'Ocean Blue',
    icon: Waves,
    theme: {
      primaryColor: '#2563eb',
      backgroundColor: '#f8fafc',
      surfaceColor: '#ffffff',
      surfaceAltColor: '#eff6ff',
      textColor: '#0f172a',
      mutedTextColor: '#475569',
      borderColor: '#bfdbfe',
      linkColor: '#2563eb',
      buttonPrimaryColor: '#2563eb',
      buttonPrimaryTextColor: '#ffffff',
      buttonPrimaryHoverColor: '#1d4ed8',
      buttonSecondaryColor: '#ffffff',
      buttonSecondaryTextColor: '#1d4ed8',
      buttonSecondaryBorderColor: '#bfdbfe',
      buttonSecondaryHoverColor: '#eff6ff',
    },
  },
  {
    name: 'Emerald Health',
    icon: Leaf,
    theme: {
      primaryColor: '#059669',
      backgroundColor: '#f0fdf4',
      surfaceColor: '#ffffff',
      surfaceAltColor: '#dcfce7',
      textColor: '#052e16',
      mutedTextColor: '#4b5563',
      borderColor: '#a7f3d0',
      linkColor: '#059669',
      buttonPrimaryColor: '#059669',
      buttonPrimaryTextColor: '#ffffff',
      buttonPrimaryHoverColor: '#047857',
      buttonSecondaryColor: '#ffffff',
      buttonSecondaryTextColor: '#047857',
      buttonSecondaryBorderColor: '#a7f3d0',
      buttonSecondaryHoverColor: '#ecfdf5',
    },
  },
  {
    name: 'Midnight Dark',
    icon: MoonStar,
    theme: {
      primaryColor: '#6366f1',
      backgroundColor: '#0f172a',
      surfaceColor: '#1e293b',
      surfaceAltColor: '#334155',
      textColor: '#f1f5f9',
      mutedTextColor: '#94a3b8',
      borderColor: '#334155',
      linkColor: '#818cf8',
      buttonPrimaryColor: '#6366f1',
      buttonPrimaryTextColor: '#ffffff',
      buttonPrimaryHoverColor: '#4f46e5',
      buttonSecondaryColor: '#1e293b',
      buttonSecondaryTextColor: '#818cf8',
      buttonSecondaryBorderColor: '#4f46e5',
      buttonSecondaryHoverColor: '#312e81',
    },
  },
  {
    name: 'Rose Medical',
    icon: Flower2,
    theme: {
      primaryColor: '#e11d48',
      backgroundColor: '#fff1f2',
      surfaceColor: '#ffffff',
      surfaceAltColor: '#ffe4e6',
      textColor: '#1f1f1f',
      mutedTextColor: '#6b7280',
      borderColor: '#fecdd3',
      linkColor: '#e11d48',
      buttonPrimaryColor: '#e11d48',
      buttonPrimaryTextColor: '#ffffff',
      buttonPrimaryHoverColor: '#be123c',
      buttonSecondaryColor: '#ffffff',
      buttonSecondaryTextColor: '#be123c',
      buttonSecondaryBorderColor: '#fecdd3',
      buttonSecondaryHoverColor: '#fff1f2',
    },
  },
  {
    name: 'Amber Warm',
    icon: Sun,
    theme: {
      primaryColor: '#d97706',
      backgroundColor: '#fffbeb',
      surfaceColor: '#ffffff',
      surfaceAltColor: '#fef3c7',
      textColor: '#1c1917',
      mutedTextColor: '#78716c',
      borderColor: '#fde68a',
      linkColor: '#d97706',
      buttonPrimaryColor: '#d97706',
      buttonPrimaryTextColor: '#ffffff',
      buttonPrimaryHoverColor: '#b45309',
      buttonSecondaryColor: '#ffffff',
      buttonSecondaryTextColor: '#b45309',
      buttonSecondaryBorderColor: '#fde68a',
      buttonSecondaryHoverColor: '#fffbeb',
    },
  },
  {
    name: 'Purple Care',
    icon: Gem,
    theme: {
      primaryColor: '#7c3aed',
      backgroundColor: '#faf5ff',
      surfaceColor: '#ffffff',
      surfaceAltColor: '#f3e8ff',
      textColor: '#1e1b4b',
      mutedTextColor: '#6b7280',
      borderColor: '#ddd6fe',
      linkColor: '#7c3aed',
      buttonPrimaryColor: '#7c3aed',
      buttonPrimaryTextColor: '#ffffff',
      buttonPrimaryHoverColor: '#6d28d9',
      buttonSecondaryColor: '#ffffff',
      buttonSecondaryTextColor: '#6d28d9',
      buttonSecondaryBorderColor: '#ddd6fe',
      buttonSecondaryHoverColor: '#f5f3ff',
    },
  },
  {
    name: 'Coral Sunset',
    icon: Sunset,
    theme: {
      primaryColor: '#f97316',
      backgroundColor: '#fff7ed',
      surfaceColor: '#ffffff',
      surfaceAltColor: '#ffedd5',
      textColor: '#1c1917',
      mutedTextColor: '#78716c',
      borderColor: '#fed7aa',
      linkColor: '#ea580c',
      buttonPrimaryColor: '#f97316',
      buttonPrimaryTextColor: '#ffffff',
      buttonPrimaryHoverColor: '#ea580c',
      buttonSecondaryColor: '#ffffff',
      buttonSecondaryTextColor: '#ea580c',
      buttonSecondaryBorderColor: '#fed7aa',
      buttonSecondaryHoverColor: '#fff7ed',
    },
  },
  {
    name: 'Sky Clinic',
    icon: Cloud,
    theme: {
      primaryColor: '#0ea5e9',
      backgroundColor: '#f0f9ff',
      surfaceColor: '#ffffff',
      surfaceAltColor: '#e0f2fe',
      textColor: '#0c1a2e',
      mutedTextColor: '#4b6280',
      borderColor: '#bae6fd',
      linkColor: '#0284c7',
      buttonPrimaryColor: '#0ea5e9',
      buttonPrimaryTextColor: '#ffffff',
      buttonPrimaryHoverColor: '#0284c7',
      buttonSecondaryColor: '#ffffff',
      buttonSecondaryTextColor: '#0284c7',
      buttonSecondaryBorderColor: '#bae6fd',
      buttonSecondaryHoverColor: '#f0f9ff',
    },
  },
  {
    name: 'Forest Pine',
    icon: TreePine,
    theme: {
      primaryColor: '#16a34a',
      backgroundColor: '#f7fdf9',
      surfaceColor: '#ffffff',
      surfaceAltColor: '#dcfce7',
      textColor: '#14532d',
      mutedTextColor: '#4b7260',
      borderColor: '#86efac',
      linkColor: '#15803d',
      buttonPrimaryColor: '#16a34a',
      buttonPrimaryTextColor: '#ffffff',
      buttonPrimaryHoverColor: '#15803d',
      buttonSecondaryColor: '#ffffff',
      buttonSecondaryTextColor: '#15803d',
      buttonSecondaryBorderColor: '#86efac',
      buttonSecondaryHoverColor: '#f0fdf4',
    },
  },
  {
    name: 'Slate Pro',
    icon: Circle,
    theme: {
      primaryColor: '#475569',
      backgroundColor: '#f8fafc',
      surfaceColor: '#ffffff',
      surfaceAltColor: '#f1f5f9',
      textColor: '#0f172a',
      mutedTextColor: '#64748b',
      borderColor: '#cbd5e1',
      linkColor: '#334155',
      buttonPrimaryColor: '#334155',
      buttonPrimaryTextColor: '#ffffff',
      buttonPrimaryHoverColor: '#1e293b',
      buttonSecondaryColor: '#ffffff',
      buttonSecondaryTextColor: '#334155',
      buttonSecondaryBorderColor: '#cbd5e1',
      buttonSecondaryHoverColor: '#f1f5f9',
    },
  },
  {
    name: 'Lavender Calm',
    icon: Sparkles,
    theme: {
      primaryColor: '#a855f7',
      backgroundColor: '#fdf4ff',
      surfaceColor: '#ffffff',
      surfaceAltColor: '#fae8ff',
      textColor: '#2d1a47',
      mutedTextColor: '#7c5fa0',
      borderColor: '#e9d5ff',
      linkColor: '#9333ea',
      buttonPrimaryColor: '#a855f7',
      buttonPrimaryTextColor: '#ffffff',
      buttonPrimaryHoverColor: '#9333ea',
      buttonSecondaryColor: '#ffffff',
      buttonSecondaryTextColor: '#9333ea',
      buttonSecondaryBorderColor: '#e9d5ff',
      buttonSecondaryHoverColor: '#fdf4ff',
    },
  },
  {
    name: 'Crimson Care',
    icon: HeartPulse,
    theme: {
      primaryColor: '#dc2626',
      backgroundColor: '#fef2f2',
      surfaceColor: '#ffffff',
      surfaceAltColor: '#fee2e2',
      textColor: '#1c0a0a',
      mutedTextColor: '#7f3232',
      borderColor: '#fca5a5',
      linkColor: '#b91c1c',
      buttonPrimaryColor: '#dc2626',
      buttonPrimaryTextColor: '#ffffff',
      buttonPrimaryHoverColor: '#b91c1c',
      buttonSecondaryColor: '#ffffff',
      buttonSecondaryTextColor: '#b91c1c',
      buttonSecondaryBorderColor: '#fca5a5',
      buttonSecondaryHoverColor: '#fef2f2',
    },
  },
  {
    name: 'Teal Wellness',
    icon: Stethoscope,
    theme: {
      primaryColor: '#0d9488',
      backgroundColor: '#f0fdfa',
      surfaceColor: '#ffffff',
      surfaceAltColor: '#ccfbf1',
      textColor: '#0f2823',
      mutedTextColor: '#4a7e78',
      borderColor: '#99f6e4',
      linkColor: '#0f766e',
      buttonPrimaryColor: '#0d9488',
      buttonPrimaryTextColor: '#ffffff',
      buttonPrimaryHoverColor: '#0f766e',
      buttonSecondaryColor: '#ffffff',
      buttonSecondaryTextColor: '#0f766e',
      buttonSecondaryBorderColor: '#99f6e4',
      buttonSecondaryHoverColor: '#f0fdfa',
    },
  },
  {
    name: 'Golden Hour',
    icon: Star,
    theme: {
      primaryColor: '#ca8a04',
      backgroundColor: '#fefce8',
      surfaceColor: '#ffffff',
      surfaceAltColor: '#fef9c3',
      textColor: '#1a1500',
      mutedTextColor: '#7a6a20',
      borderColor: '#fde047',
      linkColor: '#a16207',
      buttonPrimaryColor: '#ca8a04',
      buttonPrimaryTextColor: '#ffffff',
      buttonPrimaryHoverColor: '#a16207',
      buttonSecondaryColor: '#ffffff',
      buttonSecondaryTextColor: '#a16207',
      buttonSecondaryBorderColor: '#fde047',
      buttonSecondaryHoverColor: '#fefce8',
    },
  },
  {
    name: 'Arctic White',
    icon: MountainSnow,
    theme: {
      primaryColor: '#1e40af',
      backgroundColor: '#ffffff',
      surfaceColor: '#f8fafc',
      surfaceAltColor: '#e2e8f0',
      textColor: '#0f172a',
      mutedTextColor: '#64748b',
      borderColor: '#e2e8f0',
      linkColor: '#1d4ed8',
      buttonPrimaryColor: '#1e40af',
      buttonPrimaryTextColor: '#ffffff',
      buttonPrimaryHoverColor: '#1e3a8a',
      buttonSecondaryColor: '#ffffff',
      buttonSecondaryTextColor: '#1e40af',
      buttonSecondaryBorderColor: '#bfdbfe',
      buttonSecondaryHoverColor: '#eff6ff',
    },
  },
]
